spring.application.name=CinemaResSys
server.address=0.0.0.0
server.port=8100

spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url= jdbc:postgresql://149.100.159.18:5432/CinemaResSys
spring.datasource.username=cinema_admin
spring.datasource.password=Cinematickpage123

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto= update
